name: manual build

on:
  repository_dispatch:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:


  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Clone source code
      run: |
        git clone https://github.com/rapiz1/rathole
    - name: Build the Docker image
      run: |
        cd rathole
        docker build . --file Dockerfile --tag my-image-name:$(date +%s)