name: manual build

on:
  repository_dispatch:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        include:
          - platform: amd64
            S6_ARCH: amd64
          - platform: arm
            S6_ARCH: armhf
          - platform: arm64
            S6_ARCH: aarch64
    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Clone source code
      run: |
        git clone https://github.com/rapiz1/rathole
    # - name: Build the Docker image
    #   run: |
    #     cd rathole
    #     docker build . --file Dockerfile --tag my-image-name:$(date +%s)
    #     - name: Set up Docker Buildx
    #     uses: docker/setup-buildx-action@v1
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        build-args: S6_ARCH=${{ matrix.S6_ARCH }}
        tags: xuantran94/cloudflare-ddns-telegram:${{ matrix.platform }}
        platforms: ${{ matrix.platform }}