name: manual build

on:
  repository_dispatch:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Clone source code
      run: |
        git clone https://github.com/rapiz1/rathole
    - name: Build the Docker image
      run: |
        cd rathole
        docker build . --file Dockerfile --tag rathole:$(date +%s)
    - name: Tag Image
      run: |
        docker tag rathole rathole:latest
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Push Image to Docker Hub
      run: docker push my-docker-image:latest
    # - name: Build and push
    #   uses: docker/build-push-action@v2
    #   with:
    #     context: .
    #     file: ./Dockerfile
    #     push: true
    #     # build-args: S6_ARCH=${{ matrix.S6_ARCH }}
    #     tags: xuantrandev/rathole:${{ matrix.platform }}
    #     platforms: ${{ matrix.platform }}


        
    #     jobs:
    #       build-push:
    #         runs-on: ubuntu-latest
        
    #         steps:
    #           - name: Checkout Repository
    #             uses: actions/checkout@v2
        
    #           - name: Build Docker Image
    #             run: docker build -t my-docker-image .
        
    #           - name: Tag Image
    #             run: docker tag my-docker-image my-docker-image:latest
        
    #           - name: Login to Docker Hub
    #             uses: docker/login-action@v1
    #             with:
    #               username: ${{ secrets.DOCKER_USERNAME }}
    #               password: ${{ secrets.DOCKER_PASSWORD }}
        
    #           - name: Push Image to Docker Hub
    #             run: docker push my-docker-image:latest
        