name: manual build

on:
  repository_dispatch:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Clone source code
      run: |
        git clone https://github.com/rapiz1/rathole
    - name: Build the Docker image
      run: |
        cd rathole
        docker build . --file Dockerfile -t rathole:latest
    # - name: Tag Image
    #   run: |
    #     docker tag rathole rathole:latest
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Push Image to Docker Hub
      run: |
        docker push rathole:tagname