# This is a basic workflow to help you get started with Actions

name: new release scanning
on:
  repository_dispatch:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight

jobs:
  check-release-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: 'rapiz1/rathole'  # Specify the repository name with owner
          ref: 'main'                  # Specify the branch, tag, or SHA to checkout
          # token: ${{ secrets.GITHUB_TOKEN }}  # Personal access token (PAT) for fetching the repository (use encrypted secrets)

      - name: Get latest release tag
        id: get-release-tag
        run: |
          cd rathole
          latest_tag=$(git describe --tags --abbrev=0)
          echo "::set-output name=tag::$latest_tag"

      - name: Compare tags
        run: |
          current_tag=${{ github.ref_name }}
          if [ "$current_tag" != "${{ steps.get-release-tag.outputs.tag }}" ]; then
            echo "New release tag available: ${{ steps.get-release-tag.outputs.tag }}"
          else
            echo "No new release tags."
          fi
